import React, { useEffect, useMemo, useState } from "react";
import { Award, Printer, Users, Truck } from "lucide-react";

const MESES=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
const money=n=>`₲ ${Math.round(Number(n||0)).toLocaleString("es-PY")}`;
const uid=()=>`${Date.now()}_${Math.random().toString(36).slice(2)}`;
const DEFAULT={local:{descarga:200000,sinDevolucion:100000,consumo:150000},nacional:{descarga:250000,sinDevolucion:150000,consumo:200000},ayudanteLocal:{descarga:200000,sinDevolucion:150000,consumo:0},ayudanteNacional:{descarga:250000,sinDevolucion:200000,consumo:0}};
async function getJson(k,f){try{const r=await window.storage.get(k);return r?JSON.parse(r.value):f}catch{return f}}
function cat(v){return String(v||"").toLowerCase().includes("nacional")?"Nacional":"Local"}
function month(r){if(r.mes)return r.mes;const d=r.data||r.fecha||r.competencia||r.month;if(!d)return "";const x=new Date(`${String(d).slice(0,10)}T00:00:00`);return Number.isNaN(x.getTime())?"":MESES[x.getMonth()]}
function yes(v){if(v===true)return true;return ["cumplido","cumplida","si","sí","yes","true","ok","aprobado"].includes(String(v||"").toLowerCase())}
function normalize(r,t,c){const categoria=cat(r.categoria||r.tipo||r.categoriaRuta);const key=t==="ayudante"?(categoria==="Nacional"?"ayudanteNacional":"ayudanteLocal"):(categoria==="Nacional"?"nacional":"local");const cfg=c[key]||DEFAULT[key];const descarga=yes(r.descarga??r.descargaMercaderia??r.descargaMercaderias??r.descargaCumplida);const sin=yes(r.sinDevolucion??r.sinDevolucionAverias??r.sinDevolucionPorAverias??r.averias);const consumo=t==="ayudante"?false:yes(r.consumo??r.metaConsumo??r.consumoCumplido);const actual=Number(r.consumoActual??r.promedioActual??r.promedio??r.kmL??0)||0;return {...r,id:r.id||uid(),tipo:t,categoria,mes:month(r),nombre:r.nombre||r.motorista||r.chofer||r.ayudante||"Sin nombre",placa:r.placa||r.chapa||"",descarga,sinDevolucion:sin,consumo,consumoResultado:actual?`Cumplido — ${actual.toFixed(1)} km/l`:consumo?"Cumplido":"No cumplido",total:(descarga?cfg.descarga:0)+(sin?cfg.sinDevolucion:0)+(consumo?cfg.consumo:0),cfg}}

export default function BonificacionesPage(){
 const [rows,setRows]=useState([]),[mes,setMes]=useState(""),[categoria,setCategoria]=useState(""),[nombre,setNombre]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const [a,b,h,c]=await Promise.all([getJson("bonusReviews",[]),getJson("helperBonusReviews",[]),getJson("helperAssignments",[]),getJson("bonusConfig",DEFAULT)]);const rr=[...(Array.isArray(a)?a:[]).map(x=>normalize(x,"chofer",{...DEFAULT,...c})),...(Array.isArray(b)?b:[]).map(x=>normalize(x,"ayudante",{...DEFAULT,...c}))];const existing=new Set(rr.map(x=>x.nombre));const inferred=(Array.isArray(h)?h:[]).filter(x=>x&&(x.nombre||x.ayudante)&&!existing.has(x.nombre||x.ayudante)).map(x=>normalize({...x,nombre:x.nombre||x.ayudante},"ayudante",{...DEFAULT,...c}));setRows([...rr,...inferred]);setLoading(false)})()},[]);
 const months=MESES.filter(m=>rows.some(r=>r.mes===m));const filtered=rows.filter(r=>(!mes||r.mes===mes)&&(!categoria||r.categoria===categoria)&&(!nombre||r.nombre.toLowerCase().includes(nombre.toLowerCase())));const total=filtered.reduce((s,r)=>s+r.total,0),ct=filtered.filter(r=>r.tipo==="chofer").reduce((s,r)=>s+r.total,0),ht=filtered.filter(r=>r.tipo==="ayudante").reduce((s,r)=>s+r.total,0);
 const history=useMemo(()=>{const m={};rows.forEach(r=>{const k=`${r.tipo}|${r.nombre}|${r.categoria}`;(m[k]??=[]).push(r)});return Object.entries(m).map(([k,a])=>{const [tipo,n,c]=k.split("|");const ordered=[...a].sort((x,y)=>MESES.indexOf(x.mes)-MESES.indexOf(y.mes));const last=ordered.slice(-3),maximo=tipo==="chofer"?(c==="Nacional"?600000:450000):(c==="Nacional"?450000:350000);return{tipo,nombre:n,categoria:c,last,avg:last.length?last.reduce((s,r)=>s+r.total,0)/last.length:0,best:last.length?Math.max(...last.map(r=>r.total)):0,pct:last.length?last.reduce((s,r)=>s+r.total/maximo,0)/last.length*100:0}})},[rows]);
 if(loading)return <div style={{padding:40,color:"#6E766E"}}>Cargando bonificaciones...</div>;
 return <div style={{fontFamily:"Inter,system-ui,sans-serif",color:"#22261F"}}><style>{`@media print{body *{visibility:hidden!important}#bon-print,#bon-print *{visibility:visible!important}#bon-print{position:absolute;left:0;top:0;width:100%;background:#fff!important;color:#111!important}#bon-print button{display:none!important}}`}</style>
 <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",marginBottom:18,flexWrap:"wrap",gap:10}}><div><h1 style={{margin:0,fontSize:26,textTransform:"uppercase",letterSpacing:1.5}}>Bonificaciones</h1><div style={{color:"#6E766E",fontSize:13}}>Evaluación mensual e histórico de choferes y ayudantes</div></div><button onClick={()=>window.print()} style={btn}><Printer size={15}/> Generar todos los informes en un único PDF</button></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginBottom:18}}><label style={lab}>Mes<select value={mes} onChange={e=>setMes(e.target.value)} style={inp}><option value="">Todos</option>{months.map(m=><option key={m}>{m}</option>)}</select></label><label style={lab}>Categoría<select value={categoria} onChange={e=>setCategoria(e.target.value)} style={inp}><option value="">Todas</option><option>Local</option><option>Nacional</option></select></label><label style={lab}>Nombre<input value={nombre} onChange={e=>setNombre(e.target.value)} placeholder="Buscar..." style={inp}/></label></div>
 <div id="bon-print"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><K title="Total general" value={money(total)} icon={Award}/><K title="Total choferes" value={money(ct)} icon={Truck}/><K title="Total ayudantes" value={money(ht)} icon={Users}/><K title="Beneficiarios" value={new Set(filtered.map(r=>r.nombre)).size} icon={Users}/></div>
 <Card><T>Informe mensual</T><Table rows={filtered.flatMap(r=>[<tr key={r.id+"d"}><td rowSpan="3" style={td}>{r.nombre}</td><td rowSpan="3" style={td}>{r.tipo==="ayudante"?`Ayudante ${r.categoria}`:`Chofer ${r.categoria}`}</td><td style={td}>Descarga de mercaderías</td><td style={td}>{r.descarga?"Cumplido":"No cumplido"}</td><td style={td}>{money(r.descarga?r.cfg.descarga:0)}</td><td rowSpan="3" style={{...td,fontWeight:800}}>{money(r.total)}</td></tr>,<tr key={r.id+"s"}><td style={td}>Sin devolución por averías</td><td style={td}>{r.sinDevolucion?"Cumplido":"No cumplido"}</td><td style={td}>{money(r.sinDevolucion?r.cfg.sinDevolucion:0)}</td></tr>,<tr key={r.id+"c"}><td style={td}>{r.tipo==="ayudante"?"—":"Meta de consumo promedio"}</td><td style={td}>{r.tipo==="ayudante"?"No aplica":r.consumoResultado}</td><td style={td}>{money(r.tipo==="ayudante"?0:r.consumo?r.cfg.consumo:0)}</td></tr>])}/></Card>
 <Card><T>Histórico — últimos 3 meses</T><Table rows={history.map((h,i)=><tr key={i}><td style={td}>{h.nombre}</td><td style={td}>{h.tipo==="ayudante"?`Ayudante ${h.categoria}`:`Chofer ${h.categoria}`}</td><td style={td}>{h.last.map(x=>`${x.mes}: ${money(x.total)}`).join(" · ")}</td><td style={td}>{money(h.avg)}</td><td style={td}>{money(h.best)}</td><td style={{...td,fontWeight:800}}>{h.pct.toFixed(0)}%</td></tr>)} headers={["Nombre","Categoría","Meses evaluados","Promedio 3 meses","Mejor mes","Cumplimiento"]}/></Card>
 <Card><T>Resumen de pago</T><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[["Choferes",ct],["Ayudantes",ht],["Total general",total]].map(([x,v])=><div key={x}><div style={{fontSize:11,color:"#6E766E"}}>{x}</div><strong style={{fontSize:18}}>{money(v)}</strong></div>)}</div></Card></div></div>
}
const btn={display:"inline-flex",alignItems:"center",gap:7,padding:"9px 14px",border:0,borderRadius:7,background:"#2F6B2F",color:"#fff",fontWeight:700,cursor:"pointer"};const inp={display:"block",marginTop:5,width:"100%",padding:"9px 10px",border:"1px solid #E3DFD8",borderRadius:6,fontSize:13,background:"#fff"};const lab={fontSize:12,color:"#6E766E"};const td={padding:"9px 8px",borderBottom:"1px solid #E3DFD8",textAlign:"center",verticalAlign:"middle"};const th={...td,fontSize:10.5,textTransform:"uppercase",letterSpacing:.4,color:"#6E766E"};function Card({children}){return <div style={{background:"#fff",border:"1px solid #E3DFD8",borderRadius:10,padding:16,marginBottom:16}}>{children}</div>}function T({children}){return <div style={{fontWeight:800,textTransform:"uppercase",fontSize:13,letterSpacing:.6,marginBottom:12}}>{children}</div>}function Table({rows,headers=["Nombre","Categoría","Criterio","Resultado","Bonificación","Total"]}){return <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{headers.map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={headers.length} style={{padding:20,textAlign:"center"}}>No hay históricos para los filtros seleccionados.</td></tr>}</tbody></table></div>}function K({title,value,icon:Icon}){return <Card><div style={{display:"flex",alignItems:"center",gap:10}}><Icon size={20}/><div><div style={{fontSize:20,fontWeight:800}}>{value}</div><div style={{fontSize:11,color:"#6E766E"}}>{title}</div></div></div></Card>}
